PRODUCTION = true

JOY_DEADZONE = 0.3

WIDTH = 256
HEIGHT = 224

VOLUME = 1

FULLSCREEN = false

SCALE = 3
ZOOM = 1
MSAA = 0
VSYNC = false
DEBUGDRAW = false
MARIODEBUG = false

if MARIODEBUG then
    ZOOM = 6
end

FFKEYS = {
    {
        key="+",
        val=3
    },

    {
        key="-",
        val=0.1
    }
}

WORLD_METER = 1
WORLD_METER_FACTOR = 30/WORLD_METER

BARREL_MAXSPEED = 40
BARREL_DENSITY = 100
BARREL_RADIUS = 5

GRAVITY = 500
MARIO_GRAVITY_SCALE = 0.2

MARIO_BALLSIZE = 3 -- ( ͡° ͜ʖ ͡°)
MARIO_HEIGHT = 10
MARIO_WIDTH = 10

MARIO_ARMWIDTH = 2
MARIO_ARMLENGTH = 6

MARIO_ARMOFFSET = {
    {2, -3},
    {-2, -3}
}

MARIO_LEGWIDTH = 2
MARIO_LEGLENGTH = 5

MARIO_LEGOFFSET = {
    {3, 1},
    {-2, 1}
}

MARIO_LEGLIMITS = {
    {-math.pi*0.5, math.pi*0.25}, --front leg
    {-math.pi*0.25, math.pi*0.5} --back leg
}

MARIO_LIMBWEIGHT = 0.0001
MARIO_LEGJIGGLE = 900
MARIO_ARMJIGGLE = 900
MARIO_LIMB_FRICTION = 0.05

MARIO_ACCELERATION = 40000
MARIO_MAXSPEED = 25
MARIO_STOPSPEED = 1

MARIO_JUMPFORCE = 9000
MARIO_AIRTORQUE = 70000
MARIO_MAXTORQUE = 4
MARIO_MAXJUMPSPEED = -50

MARIO_WALKER_ANGULAR_MAX = 0.2
MARIO_UPRIGHTWINDOW = math.pi/4 -- a fourth to each side
MARIO_UPRIGHTWINDOWFLIP = math.pi/2

MARIO_ANIMATION_DISTANCE = 2
MARIO_MAX_ANIMATIONSPEED = 20

MARIO_ARMSWINGFORCE = 0.4
MARIO_ARMSWINGDROPOFF = math.pi*.3

MARIO_WIGGLEIMPULSE = 1500

MARIO_FALLOVER_FORCE = 2000
MARIO_MAXVELOCITY_FROM_FALLOVER = 40

MARIO_LADDERSPEED = 20
MARIO_LADDERANIMATIONDISTANCE = 4
MARIO_LADDERANIMATIONDIST = {2, 4}

LADDER_WIDTH = 8

DONKEYKONG_GETBARRELTIME = 0 -- before throw
DONKEYKONG_IDLETIME = 0.7 -- before throw
DONKEYKONG_MIDDLETIME = 0.35 -- before throw
DONKEYKONG_HOLDPOSE = 0.4 -- after throw
DONKEYKONG_IDLEFRAMETIME = 0.8

KEY_RIGHT = "d"
KEY_LEFT = "a"
KEY_UP = "w"
KEY_DOWN = "s"
KEY_JUMP = "space"
KEY_EXIT = "escape"

CATEGORY_TEMPORARY_PASSTHROUGH_GIRDERS = 2
CATEGORY_NO_BARREL_COLLISION = 3
CATEGORY_PERMANENT_PASSTHROUGH_MARIOS = 4
CATEGORY_TEMPORARY_PASSTHROUGH_BARRELS = 5